sudo: false

language:
- php
- node_js

php:
    - 7.0

env:
  global:
  - WP_MULTISITE=1
  - PHANTOMJS_CDNURL='http://files.urldocs.com/share/phantomjs'
  - SITE_UUID='ecc3a39c-c237-415b-b8fc-b00f58e1eb69'
  - ENCRYPTION_LABEL: 889a2dd018b1

branches:
  only:
  - master
before_install:
- nvm install stable
#- openssl aes-256-cbc -K $encrypted_889a2dd018b1_key -iv $encrypted_889a2dd018b1_iv
 # -in dev-scripts/github_deploy_key.enc -out dev-scripts/github_deploy_key -d
- WP_VERSION=$( cat ./wp-includes/version.php | grep 'wp_version =' | grep -oE '[0-9][0-9]*\.[0-9][0-9]*(\.[0-9][0-9]*)*(-[0-9a-z]*)*'
  )
- echo "WP_VERSION=$WP_VERSION"
install:
- export DEV_LIB_PATH=dev-lib
- if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname
  $( readlink .travis.yml ) ); fi
- if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/XWP/wp-dev-lib.git
  $DEV_LIB_PATH; fi
- set -x
- source $DEV_LIB_PATH/travis.install.sh


script:
- source $DEV_LIB_PATH/travis.script.sh
# - source dev-scripts/builder.sh
after_script:
- source $DEV_LIB_PATH/travis.after_script.sh


after_success:
    - |
        if [ $TRAVIS_BRANCH == 'production' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
            git config --global user.name "Travis CI"
            git config --global user.email "travisci@gmail.com"
            ssh-keyscan -p 2222 codeserver.dev.$SITE_UUID.drush.in >> ~/.ssh/known_hosts
            git remote add pantheon ssh://codeserver.dev.$SITE_UUID@codeserver.dev.$SITE_UUID.drush.in:2222/~/repository.git
            git fetch pantheon
            git merge -s ours -m "Merge changes from pantheon using ours merge strategy" pantheon/master
            git push pantheon HEAD:master
            git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
            git push -q git@github.com:ForkedByObi/WordPress-Pantheon.git --tags
        fi
